// meshgen.cpp
#include "assets.hpp"
#include "Mesh.hpp"
#include <vector>
#include <glm/glm.hpp>
#include <glm/ext.hpp>
#include <GL/glew.h>
#include <memory>

std::unique_ptr<Mesh> generateCube() {
    std::vector<Vertex> V{
        // Pozice           // Normála (zatím ignorujeme) // UV souřadnice (u, v)
        {{1.0f, 1.0f, 0.0f}, {0.0f, 0.0f, 0.0f},          {1.0f, 1.0f}}, // [00]
        {{0.0f, 1.0f, 0.0f}, {0.0f, 0.0f, 0.0f},          {0.0f, 1.0f}}, // [01]
        {{1.0f, 1.0f, 1.0f}, {0.0f, 0.0f, 0.0f},          {1.0f, 0.0f}}, // [02]
        {{0.0f, 1.0f, 1.0f}, {0.0f, 0.0f, 0.0f},          {0.0f, 0.0f}}, // [03]
        {{1.0f, 0.0f, 0.0f}, {0.0f, 0.0f, 0.0f},          {1.0f, 1.0f}}, // [04]
        {{0.0f, 0.0f, 0.0f}, {0.0f, 0.0f, 0.0f},          {0.0f, 1.0f}}, // [05]
        {{0.0f, 0.0f, 1.0f}, {0.0f, 0.0f, 0.0f},          {1.0f, 0.0f}}, // [06]
        {{1.0f, 0.0f, 1.0f}, {0.0f, 0.0f, 0.0f},          {0.0f, 0.0f}}  // [07]
    };

    std::vector<GLuint> I{ 0, 1, 4, 5, 6, 1, 3, 0, 2, 4, 7, 6, 2, 3 };

    return std::make_unique<Mesh>(V, I, GL_TRIANGLE_STRIP);
}

// Generated by AI, modified by JJ
Mesh generateSphere(unsigned int sectors, unsigned int rings) {
    std::vector<Vertex> V{};
    std::vector<GLuint> I{};

    unsigned int totalSectors = sectors + 1;

    for (unsigned int r = 0; r <= rings; ++r) {
        float const R = (float)r / (float)rings;
        float const phi = -glm::pi<float>() / 2.0f + glm::pi<float>() * R;
        float const y = std::sin(phi);
        float const xz_radius = std::cos(phi);

        for (unsigned int s = 0; s <= sectors; ++s) {
            float const S = (float)s / (float)sectors;
            float const theta = 2.0f * glm::pi<float>() * S;
            float const x = std::cos(theta) * xz_radius;
            float const z = std::sin(theta) * xz_radius;

            V.push_back({ glm::vec3(x, y, z) });
        }
    }

    for (unsigned int r = 0; r < rings; ++r) {
        if (r > 0) {
            I.push_back(r * totalSectors + sectors);
            I.push_back(r * totalSectors);
        }

        for (unsigned int s = 0; s <= sectors; ++s) {
            I.push_back(r * totalSectors + s);
            I.push_back((r + 1) * totalSectors + s);
        }
    }

    return Mesh(V, I, GL_TRIANGLE_STRIP);
}